### ISSUE TITLE
developer preview pre-flight checklist

### ISSUE THREAD

**Issue by nbsp** [livekit/agents-js#12]
ever-changing list of things we need to get ready before i'd consider this stable enough to test in prod

### parity
Python agents are still unstable and we need to copy all feature changes over, currently i'm on top of this but it can change

### plugins
- [x] elevenlabs
- [ ] google†
- [ ] openai†
- [ ] deepgram†

*† STT: need to figure out how to handle wavs in Node (potentially through `rtc-node` → FFI?)*

### testing
- [ ] unit testing of specific functions
- [ ] larger-scale testing with mocked server packets
- [ ] full end-to-end testing with a secret Cloud API key in CI?

### documentation
- [x] document everything properly (#14, #15)
- [x] maybe another comment pass (i'm not good at commenting weird code)

### infra
- [x] linting and build systems in line with LiveKit standards
- [x] release systems in place
